language: c
sudo: required
install:
  - ./.travis-deps.sh
  - make
  - sudo make install
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - ./.travis-checkpatch.sh
  - cd test
  - ./run-tests.sh
