name: "Regression testing"
on: push

jobs:
  unix-testing:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, macos-10.15]
        cc: [gcc, clang]
        include:
          - os: ubuntu-18.04
            cc: gcc
            target: develop
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        shell: bash
        run: |
          ./.github/actions/install_deps.sh ${{ matrix.os }}
      - name: Build
        run: |
          make ${{ matrix.target }} -j Q= CC=${{ matrix.cc }}
      - name: Install
        run: |
          sudo make install -j Q=
      - name: Package binaries
        run: |
          mkdir $DIST_DIR
          cp rgb{asm,link,fix,gfx} $DIST_DIR
        env:
          DIST_DIR: rgbds-canary-${{ matrix.os }}-${{ matrix.cc }}-bins
      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: rgbds-canary-${{ matrix.os }}-${{ matrix.cc }}-bins
          path: rgbds-canary-${{ matrix.os }}-${{ matrix.cc }}-bins
      - name: Test
        shell: bash
        run: |
          test/run-tests.sh
